/*
 * This file is part of Solana Reference Stake Pool code.
 *
 * Copyright © 2021, mFactory GmbH
 *
 * Solana Reference Stake Pool is free software: you can redistribute it
 * and/or modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * Solana Reference Stake Pool is distributed in the hope that it
 * will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.
 * If not, see <https://www.gnu.org/licenses/agpl-3.0.html>.
 *
 * You can be released from the requirements of the Affero GNU General Public License
 * by purchasing a commercial license. The purchase of such a license is
 * mandatory as soon as you develop commercial activities using the
 * Solana Reference Stake Pool code without disclosing the source code of
 * your own applications.
 *
 * The developer of this program can be contacted at <info@mfactory.ch>.
 */

// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../src/components/AppFooter.vue')['default']
    AppFooterLink: typeof import('./../src/components/AppFooterLink.vue')['default']
    AppHeader: typeof import('./../src/components/AppHeader.vue')['default']
    Apy: typeof import('./../src/components/Apy.vue')['default']
    ClusterSelector: typeof import('./../src/components/ClusterSelector.vue')['default']
    ConnectionLost: typeof import('./../src/components/ConnectionLost.vue')['default']
    ConnectWallet: typeof import('./../src/components/ConnectWallet.vue')['default']
    CookieModal: typeof import('./../src/components/CookieModal.vue')['default']
    CopyToClipboard: typeof import('./../src/components/CopyToClipboard.vue')['default']
    CustomSection: typeof import('./../src/components/customize/CustomSection.vue')['default']
    Epoch: typeof import('./../src/components/Epoch.vue')['default']
    ErrorContainer: typeof import('./../src/components/ErrorContainer.vue')['default']
    FaqSection: typeof import('./../src/components/customize/FaqSection.vue')['default']
    FirstlookSection: typeof import('./../src/components/FirstlookSection.vue')['default']
    PasswordProtect: typeof import('./../src/components/PasswordProtect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackedAndLiquidity: typeof import('./../src/components/StackedAndLiquidity.vue')['default']
    StakeAccountItem: typeof import('./../src/components/StakeAccountItem.vue')['default']
    StakeAccountsDialog: typeof import('./../src/components/StakeAccountsDialog.vue')['default']
    StakeBox: typeof import('./../src/components/Stake/StakeBox.vue')['default']
    ThemeModeSelector: typeof import('./../src/components/ThemeModeSelector.vue')['default']
    TokenSvg: typeof import('./../src/components/Icons/TokenSvg.vue')['default']
    TotalStacked: typeof import('./../src/components/TotalStacked.vue')['default']
    WalletBalance: typeof import('./../src/components/WalletBalance.vue')['default']
  }
}

export {}
