// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../src/components/AppFooter.vue')['default']
    AppFooterLink: typeof import('./../src/components/AppFooterLink.vue')['default']
    AppHeader: typeof import('./../src/components/AppHeader.vue')['default']
    Apy: typeof import('./../src/components/Apy.vue')['default']
    ClusterSelector: typeof import('./../src/components/ClusterSelector.vue')['default']
    ConnectionLost: typeof import('./../src/components/ConnectionLost.vue')['default']
    ConnectWallet: typeof import('./../src/components/ConnectWallet.vue')['default']
    CookieModal: typeof import('./../src/components/CookieModal.vue')['default']
    CopyToClipboard: typeof import('./../src/components/CopyToClipboard.vue')['default']
    CustomSection: typeof import('./../src/components/customize/CustomSection.vue')['default']
    Epoch: typeof import('./../src/components/Epoch.vue')['default']
    ErrorContainer: typeof import('./../src/components/ErrorContainer.vue')['default']
    FaqSection: typeof import('./../src/components/customize/FaqSection.vue')['default']
    FirstlookSection: typeof import('./../src/components/FirstlookSection.vue')['default']
    PasswordProtect: typeof import('./../src/components/PasswordProtect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackedAndLiquidity: typeof import('./../src/components/StackedAndLiquidity.vue')['default']
    StakeAccountItem: typeof import('./../src/components/StakeAccountItem.vue')['default']
    StakeAccountsDialog: typeof import('./../src/components/StakeAccountsDialog.vue')['default']
    StakeBox: typeof import('./../src/components/Stake/StakeBox.vue')['default']
    ThemeModeSelector: typeof import('./../src/components/ThemeModeSelector.vue')['default']
    TokenSvg: typeof import('./../src/components/Icons/TokenSvg.vue')['default']
    TotalStacked: typeof import('./../src/components/TotalStacked.vue')['default']
    WalletBalance: typeof import('./../src/components/WalletBalance.vue')['default']
  }
}

export {}
