export { BackpackWalletAdapter } from './adapters/BackpackWalletAdapter'
export { BybitWalletAdapter } from './adapters/BybitWalletAdapter'
export { GateWalletAdapter } from './adapters/GateWalletAdapter'
export { IframeWalletAdapter } from './adapters/IframeWalletAdapter'
export { LedgerWalletAdapter, LedgerWalletName } from './adapters/LedgerWalletAdapter'
export { OKXWalletAdapter } from './adapters/OkxWalletAdapter'
export { TorusWalletAdapter } from './adapters/TorusWalletAdapter'
export { MoongateWalletAdapter2, MoongateWalletName } from '@moongate/moongate-adapter'
export { AvanaWalletAdapter } from '@solana/wallet-adapter-avana'
export { BitgetWalletAdapter } from '@solana/wallet-adapter-bitkeep'
export { BitpieWalletAdapter } from '@solana/wallet-adapter-bitpie'
export { CloverWalletAdapter } from '@solana/wallet-adapter-clover'
export { Coin98WalletAdapter } from '@solana/wallet-adapter-coin98'
export { CoinbaseWalletAdapter } from '@solana/wallet-adapter-coinbase'
export { CoinhubWalletAdapter } from '@solana/wallet-adapter-coinhub'
export { ExodusWalletAdapter } from '@solana/wallet-adapter-exodus'
export { FractalWalletAdapter } from '@solana/wallet-adapter-fractal'
export { HuobiWalletAdapter } from '@solana/wallet-adapter-huobi'
export { HyperPayWalletAdapter } from '@solana/wallet-adapter-hyperpay'
export { KeystoneWalletAdapter } from '@solana/wallet-adapter-keystone'
export { KrystalWalletAdapter } from '@solana/wallet-adapter-krystal'
export { MagicEdenWalletAdapter, MagicEdenWalletName } from '@solana/wallet-adapter-magiceden'
export { MathWalletAdapter } from '@solana/wallet-adapter-mathwallet'
export { NekoWalletAdapter } from '@solana/wallet-adapter-neko'
export { NightlyWalletAdapter } from '@solana/wallet-adapter-nightly'
export { NufiWalletAdapter } from '@solana/wallet-adapter-nufi'
export { OntoWalletAdapter } from '@solana/wallet-adapter-onto'
export { PhantomWalletAdapter, PhantomWalletName } from '@solana/wallet-adapter-phantom'
export { SafePalWalletAdapter } from '@solana/wallet-adapter-safepal'
export { SaifuWalletAdapter } from '@solana/wallet-adapter-saifu'
export { SalmonWalletAdapter } from '@solana/wallet-adapter-salmon'
export { SkyWalletAdapter } from '@solana/wallet-adapter-sky'
export { SolflareWalletAdapter, SolflareWalletName } from '@solana/wallet-adapter-solflare'
export { SolongWalletAdapter } from '@solana/wallet-adapter-solong'
export { SpotWalletAdapter } from '@solana/wallet-adapter-spot'
export { TokenaryWalletAdapter } from '@solana/wallet-adapter-tokenary'
export { TokenPocketWalletAdapter } from '@solana/wallet-adapter-tokenpocket'
// export { BackpackWalletAdapter } from '@solana/wallet-adapter-backpack'
// export { SolanaWalletAdapter as TorusWalletAdapter } from '@web3auth/torus-solana-adapter'
// export { TorusWalletAdapter, TorusWalletName } from '@solana/wallet-adapter-torus'
export { TrezorWalletAdapter, TrezorWalletName } from '@solana/wallet-adapter-trezor'
export { TrustWalletAdapter } from '@solana/wallet-adapter-trust'
export { XDEFIWalletAdapter } from '@solana/wallet-adapter-xdefi'
export { TipLinkWalletAdapter } from '@tiplink/wallet-adapter'
export { WalletConnectWalletAdapter } from '@walletconnect/solana-adapter'
