name: Development Build and Deploy
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
#env:
#  URL:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.URL }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'

      - name: Build
        run: |
          cd build
          yarn
          yarn build
          cp dist/index.html dist/404.html
          echo ${{ env.URL }} > dist/CNAME
          yarn run deploy:gh-pages
