name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - public/**
      - src/**

#env:
#  URL: example.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm run build:staging
          cp dist/index.html dist/404.html
#          echo ${{ env.URL }} > dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
